---
title: "Número de habitantes por município"
output: html_notebook
---

```{r setup}
if(!require(pacman)) install.packages("pacman")
pacman::p_load(tidyverse)
pacman::p_load(sidrar)
pacman::p_load(pins)
pacman::p_load(brmap)
pacman::p_load(scales)
pacman::p_load(gganimate)
pacman::p_load(transformr)
pacman::p_load(gifski)
```

```{r data_import}
# populacao <- get_sidra(6579, period = "all", geo = "City", format = 3) %>% as_tibble()
# pin(populacao)

map_data <-
  pin_get("populacao") %>%
  mutate(
    municipio_cod = as.numeric(`Município (Código)`),
    ano = as.numeric(Ano)
    ) %>%
  right_join(brmap::brmap_municipio_simples, by = "municipio_cod") %>%
  filter(!is.na(Valor))

map_data <- st_as_sf(map_data)
```


```{r mapa}
p <- ggplot(map_data) +
  labs(title = "Ano: {current_frame}") +
  geom_sf(aes(fill = Valor), color = NA) +
  coord_sf(datum = NA) +
  scale_fill_distiller(name = "População", palette = "YlOrRd", trans = "log10", labels = scales::label_number_si()) +
  transition_manual(ano)

animate(p, renderer = gifski_renderer())
anim_save("mapa.gif")
```


```{r quantis}
# quantis <- map_data %>%
#   filter(ano == 2019) %>%
#   mutate(bin = cut(Valor, breaks =
#                      c(min(Valor)-1, quantile(Valor, probs = seq(0.2, 1, by = 0.2)), max(Valor)+1)))

quantis <-
  map_data %>%
  filter(ano == 2019) %>%
  mutate(bin = cut(Valor,
                   breaks = c(0, 4600, 8500, 15000, 30000, max(Valor)+1),
                   labels = c("Até 4.600", "Até 8.500", "Até 15.000", "Até 30.000", "Até 13 mi")))

ggplot(quantis) +
  geom_sf(aes(fill = bin), color = NA) +
  coord_sf(datum = NA) +
  scale_fill_brewer(palette = "Spectral")
  # scale_fill_viridis_d(direction = -1)
```

